rosy: Patch qti-telephony-common.jar
Patch qti-telephony-common.jar from LA.UM.8.6.r1-04400-89xx.0

https://github.com/LineageOS/android_frameworks_opt_telephony has yet to merge
apis related to the split of UICC records in two groups. So it's still missing
a new method getEssentialRecordsLoaded() used in blobs from recent caf tags.

Replace it with getRecordsLoaded() like previous caf releases to fix the error:

E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getEssentialRecordsLoaded()Z
in class Lcom/android/internal/telephony/uicc/IccRecords; or its super classes (declaration of
'com.android.internal.telephony.uicc.IccRecords' in /system/framework/telephony-common.jar)